class MyException(exception):
    pass

class Calculator:
    def add(self, x, y):
        if 
        return x + y